package com.patipp.sessions.api;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public final class SessionDtos {

    private SessionDtos() {
    }

    /**
     * @param mode            defaults to PRACTICE
     * @param length          null falls back to the preparation type's default rather than a
     *                        number written into the code
     * @param durationMinutes exams only; null falls back to the blueprint
     * @param seed            reproduces an earlier paper exactly. Normally omitted and
     *                        generated by the server, which then stores it on the session.
     */
    public record StartSessionRequest(
            String mode,
            @Min(1) @Max(200) Integer length,
            @Min(1) @Max(360) Integer durationMinutes,
            Long seed,
            List<UUID> subjectIds,
            List<UUID> topicIds,
            List<String> types,
            List<String> difficulties) {
    }

    /**
     * @param answer          shape depends on the question format: {@code optionIds} for
     *                        choice questions, {@code value} for true/false, {@code text} for
     *                        short answer, {@code grade} for flashcards
     * @param responseTimeMs  measured by the client. Used for pacing feedback and, from
     *                        Phase 6, to tell recall apart from working it out.
     * @param confidence      optional 1-4 self-report
     * @param clientAttemptId optional idempotency key for offline replay in Phase 9
     */
    public record SubmitAnswerRequest(
            @NotNull Integer position,
            @NotNull Map<String, Object> answer,
            @Min(0) Integer responseTimeMs,
            @Min(1) @Max(4) Integer confidence,
            UUID clientAttemptId) {
    }

    /** The question as the learner sees it: no answer key, no explanation. */
    public record ServedItem(
            int position,
            UUID questionId,
            String type,
            String difficulty,
            UUID subjectId,
            UUID topicId,
            int estimatedSeconds,
            String stem,
            List<String> hints,
            /**
             * The payload with anything that gives the answer away removed. Sending the full
             * payload and hiding it in the UI would put the answer key in the browser, where
             * anyone can read it.
             */
            Map<String, Object> presentation,
            /**
             * Why the engine chose this question, in terms the learner can be shown.
             * Recorded when the session is built rather than reconstructed afterwards - a
             * reason worked out after the fact is a guess. Contains nothing that gives the
             * answer away.
             */
            Map<String, Object> selectionReason) {
    }

    public record SessionResponse(
            UUID id,
            String mode,
            String status,
            Instant startedAt,
            Instant deadlineAt,
            Instant submittedAt,
            int totalItems,
            int answeredCount,
            int correctCount,
            long activeMs,
            boolean immediateFeedback,
            /** True for exams: the learner may jump between questions and come back. */
            boolean freeNavigation,
            /**
             * Milliseconds left, computed by the server from its own clock. Null when the
             * session has no deadline. The browser renders a countdown from this, but the
             * server is what decides when time is actually up.
             */
            Long remainingMs,
            /** Every question's position and state, for the navigation grid. */
            List<ItemSummary> items,
            /** Null once every question has been answered. */
            ServedItem currentItem) {
    }

    /**
     * One cell of the navigation grid.
     *
     * @param state UNSEEN, VIEWED, ANSWERED, MARKED_FOR_REVIEW or SKIPPED. Deliberately not
     *              whether it was <em>correct</em>: in an exam that is withheld until the end.
     */
    public record ItemSummary(int position, String state, boolean answered) {
    }

    /**
     * @param correct     null when the mode defers feedback. Withheld from the response body
     *                    rather than merely hidden by the client: an exam that sends the
     *                    verdict and asks the browser not to show it has not withheld
     *                    anything, since the network tab is one keypress away.
     * @param score       null for the same reason - a score of 0.0 says as much as
     *                    {@code correct: false}
     * @param explanation only present when the mode reveals feedback immediately; an exam
     *                    returns it in the summary instead
     */
    public record AnswerResult(
            int position,
            Boolean correct,
            Double score,
            String note,
            String explanation,
            Map<String, Object> correctAnswer,
            int answeredCount,
            int totalItems,
            boolean sessionComplete,
            ServedItem nextItem) {
    }

    public record SessionSummary(
            UUID id,
            String mode,
            String status,
            Instant startedAt,
            Instant submittedAt,
            long activeMs,
            int totalItems,
            int answeredCount,
            int correctCount,
            Double score,
            Map<String, Object> breakdown,
            List<ReviewItem> items) {
    }

    /** One line of the post-session review, with everything now revealed. */
    public record ReviewItem(
            int position,
            UUID questionId,
            String type,
            String difficulty,
            String stem,
            boolean correct,
            double score,
            String note,
            String explanation,
            Map<String, Object> yourAnswer,
            Map<String, Object> correctAnswer,
            int timeSpentMs,
            Map<String, Object> selectionReason) {
    }

    public record SessionListEntry(
            UUID id,
            String mode,
            String status,
            Instant startedAt,
            Instant submittedAt,
            int totalItems,
            int answeredCount,
            int correctCount,
            Double score) {
    }

    /** What is available to practise right now, shown before a session is started. */
    public record SessionAvailability(int availableQuestions, int suggestedLength) {
    }

    /* -------------------------------------------------------------- exam templates */

    public record SaveTemplateRequest(
            @NotNull @Size(min = 1, max = 120) String name,
            @Min(1) @Max(200) Integer length,
            @Min(1) @Max(360) Integer durationMinutes,
            List<UUID> subjectIds,
            List<UUID> topicIds,
            List<String> types,
            List<String> difficulties) {
    }

    /**
     * A saved exam setup.
     *
     * @param timesUsed how often it has been sat, so the one you actually use can be offered
     *                  first rather than the one you happened to create first
     */
    public record ExamTemplateResponse(
            UUID id,
            String name,
            Integer length,
            Integer durationMinutes,
            List<UUID> subjectIds,
            List<String> types,
            List<String> difficulties,
            int timesUsed,
            Instant lastUsedAt,
            Instant createdAt) {
    }
}
